grpc:
  port: ${GRPC_PORT}
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: "loggers"